# Generated by Django 3.2.10 on 2022-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact'),
    ]

    operations = [
    ]
